safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   date
paginate:    10
regeneration: auto
exclude: [Guardfile, .DS_Store]

redcarpet:
  extensions: []

